receivers:
  otlp:
    protocols:
      http: {}
      grpc: {}

exporters:
  logging:
    loglevel: info

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
