services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-app-skeleton.test}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./infra/caddy/certs:/etc/certs:ro
    depends_on:
      web:
        condition: service_started

volumes:
  caddy_data:
  caddy_config:

